const cloudinary = require("cloudinary").v2;
const {
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} = require("./config");

cloudinary.config({
  cloud_name: CLOUDINARY_CLOUD_NAME,
  api_key: CLOUDINARY_API_KEY,
  api_secret: CLOUDINARY_API_SECRET,
});

// const image = "./path/to/image.jpg"; // This can also be a remote URL or a base64 DataURI
const upload = async (image) => {
  try {
    const res = await cloudinary.uploader.upload(image);
    return res;
  } catch (error) {
    console.error(error);
  }
};

module.exports = { upload };

// cloudinary.uploader.upload(image, { tags: "basic_sample" }, (err, image) => {
//   console.log("** File Upload");
//   if (err) {
//     console.warn(err);
//   }
//   console.log(
//     "* public_id for the uploaded image is generated by Cloudinary's service."
//   );
//   console.log("* " + image.public_id);
//   console.log("* " + image.url);
// });
